config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/search", to: "pages#search"

  resources :profiles, except: %i[index destroy] do
    resources :reviews, only: %i[new create]
    resources :trips, only: %i[new create edit update]
    resources :enrollments, only: %i[new create edit update]
  end

  resources :trips, only: [:index]
  resources :enrollments, only: [:index]

  resources :reviews, only: [:destroy]
  resources :crags
  resources :chatrooms, only: %i[show new create index] do
    resources :messages, only: :create
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :crag
  belongs_to :user
  has_many :enrollments
  has_one :profile, through: :user
  validates :start_date, :end_date, :crag_id, presence: true
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_profile

  def index
    # turning the date string into a date instance
    # splits the string at the underscore
    # makes an array of integers
    start_date_array = params[:start_date].split("_").map { |string| string.to_i }
    end_date_array = params[:end_date].split("_").map { |string| string.to_i }

    # makes a date instance from the date arrays
    start_date = Date.new(start_date_array[0], start_date_array[1], start_date_array[2])
    end_date = Date.new(end_date_array[0], end_date_array[1], end_date_array[2])
    # daterange from start_date to end_date
    query_date_range = start_date..end_date

    crag = Crag.find(params[:crag_id])

    # filter trips
    # @trips is all trips for a certain crag
    @trips = crag.trips
    @trips = @trips.map do |trip|
      trip_date_range = trip.start_date..trip.end_date
      # if the dates overlap && both are going to the same crag
      if trip_date_range.overlaps?(query_date_range) # && trip.crag ==
        trip
      else
        next
      end
    end
    # removes all nil values of array
    @trips = @trips.compact

    respond_to do |format|
      format.html
      # render partial (movies/list)
      format.text { render partial: "crags/partials/travelling_climbers", locals: { trips: @trips }, formats: [:html] }
    end

    # raise
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    if @trip.save
      redirect_to profile_path(@profile)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    #@profile.user = current_user
    @crag = @trip.crag
    @trip.update(trip_params)

    respond_to do |format|
      format.html { redirect_to profile_path(@profile) }
      format.text { render partial: "trip_info", locals: { profile: @profile, trip: @trip }, formats: [:html] }
    end
  end

  private

  def set_profile
    if Profile.exists?(params[:profile_id])
      @profile = Profile.find(params[:profile_id])
    end
  end

  def trip_params
    params.require(:trip).permit(:name, :start_date, :end_date, :crag_id)
  end
end

app/views/trips/_form.html.erb
<div data-controller="flatpickr" class="flatpickr-form-wrapper">
  <%= simple_form_for [@profile, @trip] do |f| %>
    <%= f.input :start_date, label: "Start Date", as: :string, required: true,
                input_html: {class: "datepicker"} %>
    <%= f.input :end_date, label: "End Date", as: :string, required: true,
                input_html: {class: "datepicker"} %>
    <%= f.association :crag, include_blank: "Select a crag" %>
    <%= f.submit class: "button--red mt-4" %>
  <% end %>
</div>

app/views/trips/_trip_info.html.erb
<div data-edit-trip-target="infos">
  <div class="crag-photo"
      style="background-image: url('<%= cl_image_path trip.crag.photo.key, crop: :fill %>')">
  </div>

  <div class="container">
    <div class = "trip-infos p-1 pt-3">
      <p><strong><%= trip.crag.name %></strong></p>
      <p><%= trip.start_date %> ⇨ <%= trip.end_date %></p>
      <div class="py-3"></div>
      <% if profile.user == current_user %>
        <div class="d-flex justify-content-between align-items-center">
          <div class="button--red small" aria-label="Edit Trip">
            <i class="fa-solid fa-pen fa-lg" data-action="click->edit-trip#displayForm"></i>
          </div>
          <% if trip == profile.trips.last %>
            <%= link_to "Add another Trip", new_profile_trip_path(@profile), class: "button--red" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/edit.html.erb
<h1>Edit your trip</h1>

app/views/trips/new.html.erb
<div class="container">
  <h1>Where are you climbing next?</h1>
  <%= render "form" %>
</div>