config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/search", to: "pages#search"

  resources :profiles, except: %i[index destroy] do
    resources :reviews, only: %i[new create]
    resources :trips, only: %i[new create edit update]
    resources :enrollments, only: %i[new create edit update]
  end

  resources :trips, only: [:index]
  resources :enrollments, only: [:index]

  resources :reviews, only: [:destroy]
  resources :crags
  resources :chatrooms, only: %i[show new create index] do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 notice-ours" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 alert-ours" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-full-height navbar-main d-flex justify-content-between align-items-center" data-controller="<%= params[:controller] + params[:action] != "chatroomsshow" && "notification-subscription"  %>" data-notification-subscription-user-id-value="<%= current_user&.id %>">
  <%= link_to root_path, class: "navbar-button" do %>
    <i class="icon-nav fa-solid fa-house"></i></i>
  <% end %>
  <div class="navbar-pipe"></div>
    <%= link_to chatrooms_path, class: "navbar-button" do %>
      <i class="icon-nav fa-solid fa-message"></i>
      <div data-notification-subscription-target="inbox" class="count"><%= "(#{current_user.unread_messages.count})" if current_user&.unread_messages&.any? %></div>
    <% end %>
  <div class="navbar-pipe"></div>
    <% if user_signed_in? %>
      <% if current_page?(controller: 'profiles', action: 'show', id: current_user.id) %>
        <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "navbar-button" do %>
          <i class="icon-nav fa-solid fa-right-from-bracket"></i>
        <% end %>
      <% elsif user_signed_in? && !current_user.profile %>
        <%= link_to new_profile_path, class: "navbar-button" do %>
          <i class="icon-nav fa-solid fa-user"></i>
        <% end %>
      <% elsif user_signed_in? %>
        <%= link_to profile_path(current_user.profile), class: "navbar-button" do %>
          <i class="icon-nav fa-solid fa-user"></i>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "navbar-button" do %>
        <i class="icon-nav fa-solid fa-right-from-bracket"></i>
      <% end %>
    <% end %>
</div>

app/views/shared/_notification.html.erb
<p>(<%= count %>)</p>

app/views/shared/_profile_cards.html.erb
<% @profiles.each do |profile| %>
  <%= link_to profile_path(profile), class:"card-button p-3 my-3 d-flex flex-row align-items-start justify-content-start" do %>
        <div class="avatar-wrapper">
          <div class="avatar--small"
              style="background-image: url('<%= cl_image_path profile.photo.key,
                                                height: 100, width: 100, crop: :fill, gravity: :face %>');">
          </div>
        </div>
        <div class="card-text align-items-start">
          <h2 class="t2 t2-p"><%= profile.name %></h2>
          <h3 class="t3 t3-np text-left">home crag:</h3>
          <p class="p p-nm text-left"><%= profile.crag.name %></p>
        </div>
  <% end %>
<% end %>

app/views/shared/_search_bottom.html.erb
<div class="search-bottom">
  <%= link_to search_path, class: "search-bar search-link" do %>
      <p class="search-bar-text">Where do you want to climb? 🔎</p>
  <% end %>
</div>