config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/search", to: "pages#search"

  resources :profiles, except: %i[index destroy] do
    resources :reviews, only: %i[new create]
    resources :trips, only: %i[new create edit update]
    resources :enrollments, only: %i[new create edit update]
  end

  resources :trips, only: [:index]
  resources :enrollments, only: [:index]

  resources :reviews, only: [:destroy]
  resources :crags
  resources :chatrooms, only: %i[show new create index] do
    resources :messages, only: :create
  end
end

app/views/pages/_results.html.erb
<% results.each do |result| %>
  <% crag_id = result.searchable_id %>
  <% if Crag.exists?(crag_id) %>
    <% cloudinary_key = Crag.find(crag_id).photo.key %>
    <%= link_to crag_path(crag_id), class: "result-button", style: "background-image: url('#{cl_image_path(cloudinary_key, :crop => :fill)}'), linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5));" do %>
      <h3 class="t3 white"><%= result.content %></h3>
    <% end %>
  <% end %>
<% end %>

app/views/pages/home.html.erb
<div class="banner">
  <div class="overlay">
    <div class="container text-center">
      <%= image_tag "logo.png", class: "banner-logo" %>
      <div class="py-1"></div>
      <h3 class="t3">Climb in new places with new people!</h3>
      <div class="py-1"></div>
      <%= link_to "Checkout Areas!", search_path, class: "button--red" %>
    </div>
  </div>
</div>

<div class="container d-flex flex-column align-items-center"><%= render "shared/profile_cards" %></div>

<div class="search-bottom-padding"></div>
<%= render "shared/search_bottom" %>

app/views/pages/search.html.erb
<div data-controller="search" class="background-blue pt-4">
  <h3 class="t3 white pt-2">Where do you want to climb?</h3>
  <%= form_with url: search_path, method: :get, html: {class:
    "container", data: {search_target: "form"}} do |f| %>
    <%= f.text_field :query,
                      class: "form-control",
                      placeholder: "Search for a Crag or Country",
                      value: params[:query],
                      data: {search_target: "input",
                             action: "keyup->search#update"} %>
  <% end %>
  <div class="search-results-list" data-search-target="list"></div>
</div>